[package]
name = "day10"
version = "0.1.0"
authors = ["Eugene Korbut <me@mvl.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-rational = "0.2"
rayon = "1.1"
